spring:
  application:
    name: gzip

# server:
#   compression:
#     enabled: true
#     mime-types: application/json,application/xml,text/html,text/xml,text/plain
#     min-response-size: 1024 # in bytes, adjust as needed
